# Generated by Django 3.2.4 on 2021-06-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nombre',
        ),
    ]
