# Generated by Django 3.2.4 on 2021-07-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_auto_20210703_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
